mysql:
  host: localhost
  db:   database-name
  user: database-user
  pass: password-goes-here
  port: 3306
map:
  googlekey: google-maps-api-key-goes-here
secret:
  key: secret-key-you-can-post-goes-here
